import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav class="h-full bg-primary-200 flex flex-col justify-between">
          <ul class="flex flex-col py-2 px-4">
            <li>Liste</li>
            <li>Favoris</li>
          </ul>
        </nav>
        {children}
        </body>
    </html>
  )
}
